import { useCallback, useEffect, useRef, useState } from "react";
import { Alert, Button, Card, Collapse, Empty, Input, InputNumber, Modal, Select, Space, Switch, Tabs, Timeline, Typography } from "antd";
import type { WorkflowDefinition, WorkflowNode, WorkflowRun, WorkflowNodeType } from "../../shared/workflow";
import { workflowNodeTypes } from "../../shared/workflow";
import type { AgentDefinition, SkillDefinition, ToolDefinition } from "../../shared/studio";
import type { Snapshot } from "../../shared/types";
import { permissionLabels, type AgentPermission } from "../../shared/agent";
import { call, reportError } from "../api";
import RiskDetails from "../components/RiskDetails";
const defaults:Record<WorkflowNodeType,Record<string,unknown>>={Start:{},End:{},Input:{required:["instruction"]},Tool:{tool:"host_resources",arguments:{}},Verify:{tool:"http_check",arguments:{url:{$ref:"input.url"}}},Agent:{agentId:"template.inspection",instruction:{$ref:"input.instruction"}},Skill:{skillId:"linux-inspection"},Condition:{left:{$ref:"input.ready"},op:"eq",right:true},Approval:{toolNodeId:"tool1"},Retry:{retryTarget:"tool1",maxRetries:2,backoff:3},Wait:{seconds:5},Output:{value:{$ref:"input.instruction"}}};
const labels:Record<WorkflowRun["status"],string>={running:"执行中",paused:"已暂停",awaiting_input:"等待输入",awaiting_approval:"等待审批",awaiting_agent:"等待子Agent",unknown:"待核实",completed:"已完成",failed:"失败",cancelled:"已停止"};
export default function WorkflowStudio(){
 const [definitions,setDefinitions]=useState<WorkflowDefinition[]>([]),[draft,setDraft]=useState<WorkflowDefinition>(),[selected,setSelected]=useState("");
 const [tools,setTools]=useState<ToolDefinition[]>([]),[skills,setSkills]=useState<SkillDefinition[]>([]),[agents,setAgents]=useState<AgentDefinition[]>([]),[data,setData]=useState<Snapshot>();
 const [configText,setConfigText]=useState("{}"),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [runs,setRuns]=useState<WorkflowRun[]>([]),[runId,setRunId]=useState(""),[runOpen,setRunOpen]=useState(false),[inputText,setInputText]=useState('{}'),[hostId,setHost]=useState(""),[root,setRoot]=useState("/"),[permission,setPermission]=useState<AgentPermission>("confirm"),[sudo,setSudo]=useState(false),[supplement,setSupplement]=useState("{}");
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{id:string;dx:number;dy:number}|undefined>(undefined);
 const load=useCallback(async()=>{const [d,t,s,a,p]=await Promise.all([call<WorkflowDefinition[]>("studio.workflow.list"),call<ToolDefinition[]>("studio.tool.list"),call<SkillDefinition[]>("studio.skill.list"),call<AgentDefinition[]>("studio.agent.list"),call<Snapshot>("snapshot")]);setDefinitions(d);setTools(t);setSkills(s);setAgents(a);setData(p);},[]);
 const loadRuns=useCallback(async()=>setRuns(await call<WorkflowRun[]>("studio.workflow.runs")),[]);
 useEffect(()=>{void load().catch(reportError);void loadRuns().catch(reportError);let timer:ReturnType<typeof setTimeout>;const off=window.sre?.subscribe(e=>{if(e.type==="changed"){clearTimeout(timer);timer=setTimeout(()=>void loadRuns().catch(reportError),200);}});return()=>{clearTimeout(timer);off?.();};},[load,loadRuns]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load();await loadRuns();}catch(e){reportError(e);}finally{setBusy(false);}};
 const node=draft?.nodes.find(n=>n.id===selected),run=runs.find(r=>r.id===runId);
 const choose=(d:WorkflowDefinition)=>{setDraft(structuredClone(d));setSelected("");setNotice("");};
 const selectNode=(n:WorkflowNode)=>{setSelected(n.id);setConfigText(JSON.stringify(n.config,null,2));};
 const patchNode=(update:Partial<WorkflowNode>)=>setDraft(d=>d?{...d,nodes:d.nodes.map(n=>n.id===selected?{...n,...update}:n)}:d);
 const graph=()=>{if(!draft)throw new Error("请先选择流程");return {name:draft.name,description:draft.description,nodes:draft.nodes};};
 const add=(type:WorkflowNodeType)=>{if(!draft)return;let i=draft.nodes.length+1;while(draft.nodes.some(n=>n.id===`${type.toLowerCase()}${i}`))i++;const n:WorkflowNode={id:`${type.toLowerCase()}${i}`,type,label:type,x:40+(i%3)*220,y:40+Math.floor(i/3)*120,config:structuredClone(defaults[type])};setDraft({...draft,nodes:[...draft.nodes,n]});selectNode(n);};
 const targets=draft?.nodes.filter(n=>n.id!==selected).map(n=>({value:n.id,label:`${n.label} (${n.id})`}))??[];
 const point=(e:React.PointerEvent)=>{const box=svg.current!.getBoundingClientRect();return {x:(e.clientX-box.left)*(1000/box.width),y:(e.clientY-box.top)*(Math.max(600,...(draft?.nodes.map(n=>n.y+140)??[]))/box.height)};};
 return <>
 <div className="studio-toolbar workflow-toolbar"><Typography.Title level={4}>Workflow Studio · 工作流</Typography.Title><Space wrap>
  <Select aria-label="选择工作流" placeholder="选择流程或模板" style={{width:250}} value={draft?.id||undefined} options={definitions.map(d=>({value:d.id,label:`${d.name} v${d.version}`}))} onChange={id=>choose(definitions.find(d=>d.id===id)!)}/>
  <Button onClick={()=>choose({id:"",name:"新工作流",description:"",version:"未保存",digest:"",source:"custom",createdAt:"",updatedAt:"",nodes:[{id:"start",type:"Start",label:"开始",x:50,y:50,config:{},next:"end"},{id:"end",type:"End",label:"结束",x:300,y:50,config:{}}]})}>新建流程</Button>
  <Button disabled={!draft||busy} onClick={()=>action(async()=>{await call("studio.workflow.validate",graph());setNotice("流程结构验证通过");})}>验证流程</Button>
  <Button type="primary" disabled={!draft||busy} onClick={()=>action(async()=>{const saved=await call<WorkflowDefinition>("studio.workflow.save",{...graph(),...(draft?.id?{id:draft.id,expectedDigest:draft.digest}:{})});choose(saved);setNotice("流程已保存");})}>保存流程</Button>
  <Button disabled={!draft?.id||busy} onClick={()=>action(async()=>choose(await call("studio.workflow.clone",{id:draft!.id})))}>克隆流程</Button>
  <Button disabled={!draft?.id||busy} onClick={()=>{setInputText(JSON.stringify({instruction:"请按指定范围完成本次任务",unit:"example.service",url:"http://127.0.0.1:18101",composeFile:"compose.yaml",project:"sre-demo"},null,2));setRunOpen(true);}}>运行流程</Button>
  {draft?.source==="custom"&&draft.id&&<Button danger onClick={()=>Modal.confirm({title:"删除流程定义？",content:"历史运行快照保留。",onOk:()=>action(async()=>{await call("studio.workflow.remove",{id:draft.id});setDraft(undefined);})})}>删除流程</Button>}
 </Space>{notice&&<Alert style={{marginTop:12,width:"100%"}} type="success" title={notice}/>}</div>
 {!draft&&<Empty description="选择已保存流程，或新建流程开始编辑"/>}
 {draft&&<><Input aria-label="工作流名称" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} style={{marginBottom:8}}/><Input aria-label="工作流说明" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} style={{marginBottom:12}}/>
 <div className="workflow-workspace">
  <Card size="small" title="节点库"><Space orientation="vertical">{workflowNodeTypes.map(t=><Button key={t} size="small" onClick={()=>add(t)}>+ {t}</Button>)}</Space></Card>
  <Card size="small" title={`流程画布 · ${draft.version}`}><div style={{maxHeight:650,overflow:"auto"}}><svg ref={svg} role="img" aria-label="工作流画布" viewBox={`0 0 1000 ${Math.max(600,...draft.nodes.map(n=>n.y+140))}`} style={{width:"100%",minWidth:360,background:"var(--soft)",touchAction:"none"}} onPointerMove={e=>{if(!drag.current)return;const p=point(e);setDraft(d=>d?{...d,nodes:d.nodes.map(n=>n.id===drag.current?.id?{...n,x:Math.max(0,Math.min(800,p.x-drag.current.dx)),y:Math.max(0,Math.min(9500,p.y-drag.current.dy))}:n)}:d);}} onPointerUp={()=>{drag.current=undefined;}} onPointerCancel={()=>{drag.current=undefined;}}>
   <defs><marker id="workflow-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#598a94"/></marker></defs>
   {draft.nodes.flatMap(n=>[n.next,n.otherwise,n.onFailure,n.type==="Retry"?n.config.retryTarget:undefined].map((to,index)=>{const dest=draft.nodes.find(d=>d.id===to);return dest?<g key={`${n.id}-${index}`}><path d={`M${n.x+170} ${n.y+35} C${n.x+205} ${n.y+35},${dest.x-35} ${dest.y+35},${dest.x} ${dest.y+35}`} fill="none" stroke={index===0?"#598a94":"#bd7645"} strokeWidth="2" strokeDasharray={index?"6 4":undefined} markerEnd="url(#workflow-arrow)"/><text x={(n.x+170+dest.x)/2} y={(n.y+dest.y)/2+25} fontSize="11" fill="#54717a">{index===0?(n.type==="Condition"?"true":"next"):index===1?"false":index===2?"failure":"retry"}</text></g>:null;}))}
   {draft.nodes.map(n=><g key={n.id} transform={`translate(${n.x},${n.y})`} role="button" aria-label={`节点 ${n.id}`} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")selectNode(n);}} onPointerDown={e=>{selectNode(n);const p=point(e);drag.current={id:n.id,dx:p.x-n.x,dy:p.y-n.y};e.currentTarget.setPointerCapture(e.pointerId);}} style={{cursor:"grab"}}><rect width="170" height="70" rx="5" fill={n.id===selected?"var(--soft)":"var(--surface)"} stroke={n.id===selected?"var(--accent)":"var(--line)"} strokeWidth="2"/><text x="12" y="25" fontSize="13" fill="var(--accent)">{n.type} · {n.label.slice(0,10)}</text><text x="12" y="48" fontSize="11" fill="var(--quiet)">{n.id}</text></g>)}
  </svg></div></Card>
  <Card size="small" title="节点属性">{node?<Space orientation="vertical" style={{width:"100%"}}><Typography.Text>{node.type} · {node.id}</Typography.Text><Input aria-label="节点名称" value={node.label} onChange={e=>patchNode({label:e.target.value})}/>
   {node.type!=="End"&&<Select aria-label="下一节点" placeholder="下一节点 / true" value={node.next} options={targets} onChange={next=>patchNode({next})} style={{width:"100%"}}/>}
   {node.type==="Condition"&&<Select aria-label="条件false节点" placeholder="false分支" value={node.otherwise} options={targets} onChange={otherwise=>patchNode({otherwise})} style={{width:"100%"}}/>}
   <Select aria-label="失败节点" allowClear placeholder="失败后停止（或选择分支）" value={node.onFailure} options={targets} onChange={onFailure=>patchNode({onFailure})} style={{width:"100%"}}/>
   {["Tool","Verify"].includes(node.type)&&<Select aria-label="节点工具" value={node.config.tool} options={tools.filter(t=>node.type!=="Verify"||t.verificationCapability).map(t=>({value:t.id,label:t.name}))} onChange={tool=>{const c={...node.config,tool,arguments:{}};patchNode({config:c});setConfigText(JSON.stringify(c,null,2));}} style={{width:"100%"}}/>}
   {node.type==="Agent"&&<Select value={node.config.agentId} options={agents.map(a=>({value:a.id,label:a.name}))} onChange={agentId=>{const c={...node.config,agentId};patchNode({config:c});setConfigText(JSON.stringify(c,null,2));}} style={{width:"100%"}}/>}
   {node.type==="Skill"&&<Select value={node.config.skillId} options={skills.map(s=>({value:s.id,label:s.name}))} onChange={skillId=>{const c={skillId};patchNode({config:c});setConfigText(JSON.stringify(c,null,2));}} style={{width:"100%"}}/>}
   <Typography.Text type="secondary">配置JSON；引用格式：{'{"$ref":"input.url"}'}。编辑后点击应用。</Typography.Text><Input.TextArea aria-label="节点配置JSON" rows={12} value={configText} onChange={e=>setConfigText(e.target.value)}/><Button onClick={()=>{try{patchNode({config:JSON.parse(configText)});setNotice("节点配置已应用，保存前请验证流程");}catch(e){reportError(e);}}}>应用节点配置</Button>
   <Button danger onClick={()=>{setDraft({...draft,nodes:draft.nodes.filter(n=>n.id!==node.id)});setSelected("");}}>删除节点</Button></Space>:<Typography.Text type="secondary">选择节点配置；拖动节点调整布局。通过下一节点、false和失败分支连接。</Typography.Text>}</Card>
 </div></>}
 <Card title="流程执行记录" style={{marginTop:16}}><Select aria-label="流程运行记录" placeholder="选择运行" value={runId||undefined} onChange={setRunId} style={{width:"100%",marginBottom:12}} options={runs.map(r=>({value:r.id,label:`${r.definition.name} · ${labels[r.status]} · ${new Date(r.createdAt).toLocaleString()}`}))}/>
 {run&&<><Alert type={run.status==="failed"?"error":"info"} title={`${labels[run.status]} · ${run.current}`} description={run.summary}/><Space style={{margin:"12px 0"}}><Button disabled={busy||run.status!=="running"} onClick={()=>action(()=>call("studio.workflow.pause",{id:run.id}))}>暂停工作流</Button><Button disabled={busy||!["paused","awaiting_agent"].includes(run.status)} onClick={()=>action(()=>call("studio.workflow.resume",{id:run.id}))}>继续工作流</Button><Button disabled={busy||run.status!=="unknown"} onClick={()=>action(()=>call("studio.workflow.reconcile",{id:run.id}))}>核实与恢复</Button><Button danger disabled={busy||["completed","failed","cancelled"].includes(run.status)} onClick={()=>action(()=>call("studio.workflow.stop",{id:run.id}))}>停止后续节点</Button></Space>
 {run.pending&&<Card size="small" title={`审批操作 · 风险 ${run.pending.risk}`}>
 {run.pending.assessment&&<RiskDetails risk={run.pending.assessment}/>}
 <pre className="output">{JSON.stringify({tool:run.pending.call.tool,arguments:run.pending.call.arguments,target:run.pending.target},null,2)}</pre><Space><Button type="primary" onClick={()=>action(()=>call("studio.workflow.approve",{id:run.id,digest:run.pending!.digest,approved:true}))}>批准此操作</Button><Button danger onClick={()=>action(()=>call("studio.workflow.approve",{id:run.id,digest:run.pending!.digest,approved:false}))}>拒绝此操作</Button></Space></Card>}
 {run.status==="awaiting_input"&&<><Input.TextArea aria-label="补充流程输入" value={supplement} onChange={e=>setSupplement(e.target.value)}/><Button onClick={()=>action(()=>call("studio.workflow.input",{id:run.id,values:JSON.parse(supplement)}))}>提交缺失输入</Button></>}
 <Timeline style={{marginTop:16}} items={run.events.slice(-50).map(e=>({key:e.id,content:<><strong>{e.nodeId} · {e.kind}</strong><div>{e.summary}</div><small>{new Date(e.at).toLocaleString()}</small>{e.data!==undefined&&<Collapse size="small" items={[{key:e.id,label:"结果 / Evidence",children:<pre className="output">{JSON.stringify(e.data,null,2)}</pre>}]}/>}</>}))}/></>}
 </Card>
 <Modal title={`运行 ${draft?.name??"工作流"}`} open={runOpen} onCancel={()=>setRunOpen(false)} confirmLoading={busy} okText="启动流程" onOk={()=>action(async()=>{const r=await call<WorkflowRun>("studio.workflow.run",{id:draft!.id,target:{kind:"ssh",hostId,root,sudo},permission,input:JSON.parse(inputText)});setRunId(r.id);setRunOpen(false);})}>
  <Space orientation="vertical" style={{width:"100%"}}><Alert type="info" title="运行已保存版本；先保存画布修改。输入不会包含凭据。"/><Select aria-label="流程目标服务器" placeholder="选择已验证服务器" value={hostId||undefined} onChange={setHost} options={data?.hosts.filter(h=>h.fingerprint).map(h=>({value:h.id,label:h.name}))} style={{width:"100%"}}/><Input aria-label="流程工作目录" value={root} onChange={e=>setRoot(e.target.value)}/><Select value={permission} onChange={setPermission} options={Object.entries(permissionLabels).map(([value,label])=>({value,label}))} style={{width:"100%"}}/><Space>允许已配置sudo<Switch checked={sudo} onChange={setSudo}/></Space><Input.TextArea aria-label="流程输入JSON" rows={10} value={inputText} onChange={e=>setInputText(e.target.value)}/></Space>
 </Modal>
 </>;
}
